import Head from "next/head";
import EmployeeList from "~/components/employees";
import { NewEmployeeForm } from "~/components/form";
import { Toaster } from "~/components/ui/toaster";
import { signInWithGoogle } from "~/server/db";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="m-4">
        <div className="mb-2">
          <h1 className="text-2xl font-bold">
            Hi, My Name is Mongia Ben Hmiden
          </h1>
          <p>
            I will be your email automator today, add a new employee below to
            get started!
          </p>
        </div>
        <NewEmployeeForm />
        <h2 className="mt-12 text-2xl font-semibold">Employees List</h2>
        <EmployeeList />
      </main>
      <button onClick={signInWithGoogle}>Sign In</button>
      <Toaster />
    </>
  );
}
